Numpy: NumPy stands for Numerical python and is the core library for numeric and scientific computing

In [2]:
#numpy
import numpy as np

In [ ]:
# 1D array
n1 = np.array([10,20,30])
# to check type : nd stands for n dimentional array
print(type(n1))
# print num
print(n1)

<class 'numpy.ndarray'>
[10 20 30]


In [11]:
# Multidimensional array
n2 = np.array([[10,20,30],[40,50,60]])
print(n2[0][1])

20


In [15]:
# Initializing numpy array with zeroes
n3 = np.zeros((5,5))
print(n3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
# Initializing numpy array with same number
n4 = np.full((3,3),7)
print(n4)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [19]:
# Initializing numpy array within a range
n5 = np.arange(0,20) # 20 is exlusive
print(n5)

n6 = np.arange(5,50,5) # step size of 5
print(n6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5 10 15 20 25 30 35 40 45]


In [20]:
# Initializing numpy array with random numbers

n7 = np.random.randint(0,100,5)
print(n7)

[55 86 48  5 37]
