In [2]:
# Numpy Array Mathematics

import numpy as np

In [12]:
#Addition of NumPy Arrays

#this will return the resultant sum
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
np.sum([n1,n2])

np.int64(21)

In [5]:
#Individual sum along the the rows:

np.sum([n1,n2],axis=1)

array([ 6, 15])

In [6]:
#Individual sum along the the cols:

np.sum([n1,n2],axis=0)

array([5, 7, 9])

In [13]:
# Basic addition, subtraction, multiplication, division of a scalar value to each individual elements of numpy array

#Basic addition 

n1 = n1 + 1
print(n1)

#Basic subtraction
n2 = n2 - 1
print(n2)

#Basic multiplication
n1 = n1*10
print(n1)

#Basic division
n1 = n1/10
print(n1)

[2 3 4]
[3 4 5]
[20 30 40]
[2. 3. 4.]


In [16]:
#Some mathematical functions

#Mean : The sum of all values divided by the number of values.

n8 = np.array([10,25,30,11,50,60])
np.mean(n8)


np.float64(31.0)

In [17]:
#Median : The middle value when the data is sorted.

np.median(n8)

np.float64(27.5)

In [18]:
#Standard Devaition : Measures how spread out the values are from the mean.
# Small std dev → values are close to mean(small variation)
# Large std dev → values are widely spread(large variation)

np.std(n8)

np.float64(18.618986725025255)