In [2]:
# Numpy Matrix

import numpy as np

In [ ]:
# Accessing elements in multidimenstional array
#indexing starts from 0

n1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
n1[0]


np.int64(20)

In [10]:
#Extract 20
n1[0][1]

np.int64(20)

In [7]:
#access all row from second col
n1[:,1]

array([20, 50, 80])

In [ ]:
#NumPy Matrix Transpose : Interchanging rows and cols
print(n1)
n1.transpose()

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

In [18]:
#NumPy Matrix Multiplication : multiplying rows from one numPy array and col from another numPy array
# n2 = np.array([[1,2,3],[4,5,6]])

# n1.dot(n2)
#error dimnesions shud match

n2 = np.array([[1,6,3],[4,5,6],[7,8,10]])
n1.dot(n2)

array([[ 300,  400,  450],
       [ 660,  970, 1020],
       [1020, 1540, 1590]])

In [19]:
n2.dot(n1)

array([[ 460,  560,  660],
       [ 660,  810,  960],
       [1090, 1340, 1590]])

In [ ]:
# NumPy Save and Load

#Saving numPy array
np.save('my_numpy',n1)
print(n1,"\n")

#Load numPy array : pass the name and also give the extension npy
n3 = np.load('my_numpy.npy')
print(n3)


[[10 20 30]
 [40 50 60]
 [70 80 90]] 

[[10 20 30]
 [40 50 60]
 [70 80 90]]
