In [2]:
#Numpy Operations
import numpy as np

In [ ]:
#checking the shape(method) of NumPy Array
n1 = np.array([[10,20,30],[40,50,60]])
print(n1.shape)

#prints the dimentions of array i.e. (rows, columns)


(2, 3)


In [4]:
#Reshaping NumPy Array
n1.shape = (3,2)
print(n1)

[[10 20]
 [30 40]
 [50 60]]


In [ ]:
##Joining NumPy Arrays
#Stacking takes tuple or list of arrays
#Vstack() : one numpy array on top of another numpy array ie. vertical stacking

n2 = np.array([[1,2,3],[4,5,6]])
# np.vstack((n1,n2))
#error due to mismatched columns
n3 = np.array([[7,8],[9,10]])
np.vstack((n1,n3))


array([[10, 20],
       [30, 40],
       [50, 60],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# hstack() : one numpy array beside another numpy array ie. horizontal stacking
# np.hstack((n1,n3))
# error due to mismatched rows
np.hstack((n2,n3))

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])

In [11]:
# column_stack() : one numpy array goes in first col and another goes to the second coln
# it is mainly for 1-D arrays
n4 = np.array([1,2,3])
n5 = np.array([4,5,6])
np.column_stack((n4,n5))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#Numpy Intersection and Difference

#Intersection : returns the common elements in both the arrays
n6 = np.array([1,2,3,4,5])
n7 = np.array([4,5,6,7,8])
np.intersect1d(n6,n7)

array([4, 5])

In [ ]:
# setdiff1d() : returns all the unique  elements in first array that are not in second array
np.setdiff1d(n6,n7)


array([1, 2, 3])

In [16]:
np.setdiff1d(n7,n6)

array([6, 7, 8])